### ISSUE TITLE
Illegal byte sequence error

### ISSUE THREAD

**Issue by dan90210** [codesections/gtypist_programming_characters#3]
Just downloaded your file. Getting this error

```
$ gtypist p.typ
gtypist: line 819: iconv() failed on 'B:Lesson P11 — final lesson': Illegal byte sequence
You should probably use a UTF-8 locale for the selected lesson!
:
?
```

running on Mac with latest gtypist

**Comment by niclas-w** [comment]
This should fix it:
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by dan90210** [comment]
I added those to lines to my zshrc and I still get the same error. I can confirm that those are the locales that I am running
```

➜ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

~
➜ gtypist p.typ
gtypist: line 819: iconv() failed on 'B:Lesson P11 — final lesson': Illegal byte sequence
You should probably use a UTF-8 locale for the selected lesson!
:
?

~
➜
```

Any idea what is going on?

**Comment by niclas-w** [comment]
Nope =( That worked for me.

Until someone figures it out, you can always edit the lesson file. Change the `—` to a `-` on line 819.

```
@@ -816,7 +816,7 @@ N:MENU

 # Lesson P11—Practice with the Super Tiny Compiler
 *:PRACTICE_3
-B:Lesson P11 — final lesson
+B:Lesson P11 - final lesson
```
